//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace otel.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OtelEntities2 : DbContext
    {
        public OtelEntities2()
            : base("name=OtelEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Musteriler> Musterilers { get; set; }
        public virtual DbSet<Oteller> Otellers { get; set; }
        public virtual DbSet<Subeler> Subelers { get; set; }
        public virtual DbSet<Turlar> Turlars { get; set; }
    }
}
