//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace otel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Oteller
    {
        public int OtelNo { get; set; }
        public string OtelAdi { get; set; }
        public string İl { get; set; }
        public string Tür { get; set; }
        public Nullable<int> Yıldızı { get; set; }
    }
}
