//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace otel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Turlar
    {
        public int TurNo { get; set; }
        public string TurAdi { get; set; }
        public string İçerik { get; set; }
        public string Ulaşım { get; set; }
        public Nullable<int> KatilimSayisi { get; set; }
    }
}
